# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20190614_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='places.tags'),
        ),
    ]
