# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20190615_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['location']},
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='places.tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
